<?php
$this->headTitle('Cadastro de posts');
?>

<?php echo $this->form()->openTag($form); ?>

<div class="form-group">
    <?= $this->formElement($form->get('id')) ?>
</div>

<div class="form-group">
    <?= $this->formLabel($form->get('title')) ?>
    <?= $this->formElement($form->get('title')) ?>
    <?= $this->formElementErrors($form->get('title')) ?>
</div>

<div class="form-group">
    <?= $this->formLabel($form->get('text')) ?>
    <?= $this->formElement($form->get('text')) ?>
    <?= $this->formElementErrors($form->get('text')) ?>
</div>

<div class="form-group">
   <input type="submit" value="Cadastrar" class="btn btn-success" />
</div>


<?php echo $this->form()->closeTag(); ?>



