<?php

$this->headTitle('Listagem de posts');

?>
<h1>Post cadastrados</h1>
<div class="row">
    <div class="col-md-4 col-md-offset-10">
        <a href="<?= $this->url('posts', ['action' => 'add']) ?>" class="btn btn-info">Cadastrar Novo post</a>
    </div>
</div>
<div class="row">
    <div class="col-md-12">
        <table class="table">
            <thead>
            <tr>
                <th>ID</th>
                <th>Title</th>
                <th>Action</th>
            </tr>
            </thead>
            <?php foreach ($posts as $post): ?>
                <tbody>
                <th>
                    <td><?= $post->getId() ?></td>
                    <td><?= $post->getTitle() ?></td>
                    <td><a href="<?= $this->url('posts', ['action' => 'edit', 'id' => $post->getId()]) ?>">Edit</a> | <a href="<?= $this->url('posts', ['action' => 'delete', 'id' => $post->getId()]) ?>">Excluir</a></td>
                </th>
                </tbody>
            <?php endforeach; ?>
        </table>
    </div>
</div>
